# **Discussions 활성화**

---

  > GitHub의 디스커션은 코드 이슈와는 별도로 프로젝트와 관련된 일반적인 토론을 나눌 수 있는 기능입니다. 새로운 아이디어나 기능 제안, 사용자 피드백, 개발자 간의 토론 , 커뮤니티 멤버와의 소통외에도 본인이 습득한 지식을 공유하거나 문서화시킬 수 있는 기능입니다.
    >
    
    먼저 레퍼지토리의 **[Setting]** 탭으로 들어간 뒤, **Features** 항목의 Di**scussions**에 있는 ‘***Set up Discussions***’ 버튼을 누르면 이슈 템플릿을 등록할 수 있는 화면이 나온다.
    
    ![image.png](attachment:0de7b9e3-fe16-471f-b025-a9ddf973e28a:image.png)
  
  # **Discussions 템플릿(커스텀 가능)**

---

### 1. 카테고리 생성

  ![image.png](attachment:162d475c-62bc-49a1-a790-a2303532f55a:image.png)

  ## 2. 템플릿 커스텀 하기

- 템플릿을 작성하는 방법은 [GITHUB 공식문서](https://docs.github.com/en/discussions/quickstart)에 자세히 볼 수 있다.
  
  **STEP1.**  **`.github/DISCUSSION_TEMPLATE` 폴더 만들기**
  
  ISSUE_TEMPLATE과 달리 TEMPLATE 파일은 .yml로 관리한다.
  
  **STEP2. `category_name.yml` 만들기**
  
  카테고리 이름과 템플릿 파일이름은 반드시 같아야 한다. 대소문자는 상관없다. 나는 파일 이름을 모두 소문자로 맞췄다.
  
  **STEP3. Title과 Body 커스텀하기**
  
  **announcements.yaml**
  
  ```markdown
title: "📄 [문서] {제목을 작성해주세요}"
labels:
  - "공지"
body:
  # 안내 문구(마크다운)
  - type: markdown
    attributes:
      value: |
        <!-- 
        📢 프로젝트 공지, 제안, 방향성 공유 등을 위한 템플릿입니다.
        아래 항목에 맞춰 간단하게 내용을 작성해주세요.
        -->

  # 배경 / 맥락
  - type: textarea
    id: context
    attributes:
      label: "❗ 배경 / 맥락"
      description: "이 내용을 공유하게 된 배경이나 필요성을 간단히 적어주세요."
      placeholder: |
        - 어떤 계기로 공유하는 내용인지
        - 관련된 상황이 있다면 설명
    validations:
      required: true

  # 주요 내용
  - type: textarea
    id: content
    attributes:
      label: "📝 주요 내용"
      description: "중요한 결정 사항이나 공유하고 싶은 핵심 내용을 정리해주세요."
      placeholder: |
        - 기능 도입 여부 결정
        - 일정 변경, 역할 분배 등
        - 중요한 안내 사항
    validations:
      required: true

  # 참고 사항 (선택)
  - type: textarea
    id: additional
    attributes:
      label: "📌 추가 참고사항 (선택)"
      placeholder: |
        - 관련 링크
        - 이슈 번호
        - 회의록 등
    validations:
      required: false

  # 담당자 (선택)
  - type: textarea
    id: assignees
    attributes:
      label: "🙋 담당자 (선택)"
      placeholder: |
        - 백엔드:
        - 프론트엔드:
    validations:
      required: false

  ```

  **documents.yaml**

  ```markdown
title: "📄 [문서] {제목을 작성해주세요}"
labels:
  - "기술 문서"
body:
  # 안내 문구(마크다운)
  - type: markdown
    attributes:
      value: |
        <!-- 
        📚 구현 내역 정리, 기술 공유, 회고 등을 위한 템플릿입니다.
        아래 항목에 맞춰 자유롭게 작성해주세요.
        -->

  # 요약
  - type: textarea
    id: summary
    attributes:
      label: "📌 요약"
      description: "무엇을 다루는 문서인지 한 줄로 요약해주세요."
      placeholder: |
        - 특정 기능 구현기
        - 라이브러리 적용 후기
        - 기술적 의사결정 회고 등
    validations:
      required: true

  # 세부 내용
  - type: textarea
    id: details
    attributes:
      label: "🔍 세부 내용"
      description: "기술적인 설명, 구현 방법, 고려 사항 등을 자세히 작성해주세요."
      placeholder: |
        - 설계 방향, 코드 구조
        - 사용한 기술 및 이유
        - 적용 결과
    validations:
      required: true

  # 트러블슈팅 / 회고 (선택)
  - type: textarea
    id: troubleshooting
    attributes:
      label: "🧯 트러블슈팅 / 회고 (선택)"
      placeholder: |
        - 어떤 문제가 있었고 어떻게 해결했는지
        - 개선하고 싶은 점
    validations:
      required: false

  # 참고 자료 (선택)
  - type: textarea
    id: references
    attributes:
      label: "🔗 참고 자료 (선택)"
      placeholder: |
        - [공식 문서](https://example.com)
        - 참고한 글이나 이슈 번호 등
    validations:
      required: false

  # 담당자 (선택)
  - type: textarea
    id: assignees
    attributes:
      label: "🙋 담당자 (선택)"
      placeholder: |
        - 백엔드:
        - 프론트엔드:
    validations:
      required: false

  ```
