server:
  port: 8080

cloud:
  aws:
    credentials:
      access-key: ${AWS_S3_ACCESS_KEY:S3_ACCESS_KEY}
      secret-key: ${AWS_S3_SECRET_ACCESS_KEY:S3_SECRET_KEY}
    region:
      static: ap-northeast-2
    s3:
      bucket: ${AWS_S3_BUCKET_NAME:s3-bucket}
      url:
        prefix: "https://${AWS_S3_BUCKET_NAME:s3-bucket}.s3.ap-northeast-2.amazonaws.com"
